version: '3'
services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo  # Dịch vụ người dùng phụ thuộc vào dịch vụ MongoDB
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mongo  # Dịch vụ sản phẩm phụ thuộc vào dịch vụ MongoDB
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: